namespace: midnya
name: rlo
version: 0.4.4
readme: ./README.md
authors:
  - Midnya <github@midnya.cat>
description: Rich Live Output.
  A rich stdout callback plugin.
  Designed for humans, using modern terminals,
  with a focus on density of useful information.
repository: https://github.com/midnya/ansible-rich-live-output
license_file: ./COPYING
build_ignore:
  - .ansible
  - .git
  - .vscode
  - playbooks
  - venv
  - .gitignore
  - ansible.cfg
  - main.yml
  - main.py
  - requirements.dev.txt
